package um.canario.grupo1.models.beans;
// Generated 14-dic-2012 18:00:26 by Hibernate Tools 3.2.1.GA



/**
 * Menciones generated by hbm2java
 */
public class Menciones  implements java.io.Serializable {


     private Integer id;
     private int idUsuario;
     private int idTweet;

    public Menciones() {
    }

    public Menciones(int idUsuario, int idTweet) {
       this.idUsuario = idUsuario;
       this.idTweet = idTweet;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdTweet() {
        return this.idTweet;
    }
    
    public void setIdTweet(int idTweet) {
        this.idTweet = idTweet;
    }




}


