package um.canario.grupo1.models.beans;
// Generated 13-dic-2012 13:56:39 by Hibernate Tools 3.2.1.GA



/**
 * Relaciones generated by hbm2java
 */
public class Relaciones  implements java.io.Serializable {


     private Integer id;
     private int followed;
     private int follower;

    public Relaciones() {
    }

    public Relaciones(int followed, int follower) {
       this.followed = followed;
       this.follower = follower;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFollowed() {
        return this.followed;
    }
    
    public void setFollowed(int followed) {
        this.followed = followed;
    }
    public int getFollower() {
        return this.follower;
    }
    
    public void setFollower(int follower) {
        this.follower = follower;
    }




}


