package um.canario.grupo1.models.beans;
// Generated 11-dic-2012 0:53:23 by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Tweets generated by hbm2java
 */
public class TweetBean  implements java.io.Serializable {


     private Integer id;
     private String tweet;
     private int idUsuario;
     private Date fecha;

    public TweetBean() {
    }
    

    public TweetBean(String tweet, int idUsuario) {
       this.tweet = tweet;
       this.idUsuario = idUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTweet() {
        return this.tweet;
    }
    
    public void setTweet(String tweet) {
        this.tweet = tweet;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }



}


