package um.canario.grupo1.models.beans;
// Generated 17-dic-2012 12:00:13 by Hibernate Tools 3.2.1.GA



/**
 * Userconfig generated by hbm2java
 */
public class Userconfig  implements java.io.Serializable {


     private int idUsuario;
     private boolean notificacionesMentions;
     private boolean notificacionesFollow;
     private boolean notificacionesRetweet;

    public Userconfig() {
    }

    public Userconfig(int idUsuario, boolean notificacionesMentions, boolean notificacionesFollow, boolean notificacionesRetweet) {
       this.idUsuario = idUsuario;
       this.notificacionesMentions = notificacionesMentions;
       this.notificacionesFollow = notificacionesFollow;
       this.notificacionesRetweet = notificacionesRetweet;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public boolean getNotificacionesMentions() {
        return this.notificacionesMentions;
    }
    
    public void setNotificacionesMentions(boolean notificacionesMentions) {
        this.notificacionesMentions = notificacionesMentions;
    }
    public boolean getNotificacionesFollow() {
        return this.notificacionesFollow;
    }
    
    public void setNotificacionesFollow(boolean notificacionesFollow) {
        this.notificacionesFollow = notificacionesFollow;
    }
    public boolean getNotificacionesRetweet() {
        return this.notificacionesRetweet;
    }
    
    public void setNotificacionesRetweet(boolean notificacionesRetweet) {
        this.notificacionesRetweet = notificacionesRetweet;
    }




}


